name: Voting App Vote  CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: iamnilanjan3/vote
        tags: ${{ github.run_attempt }}, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Replace new build number
      run: sed -E -i'' "s/(.*vote:).*/\1${{ github.run_attempt }}/" 'Deployment.yml'

    - name: Show Manifest
      run: cat Deployment.yml

    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: |
       git config --global user.email "rahulgandhi2803@gmail.com"
       git config --global user.name "rahul"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
